# action.yml
name: 'run-fuzzers'
description: 'Runs fuzz target binaries for a specified length of time.'

branding:
  icon: 'shield'
  color: 'blue'

inputs:
  oss-fuzz-project-name:
    description: 'The OSS-Fuzz project name.'
    required: true

  language:
    description: 'Programming language the project is written in.'
    required: false
    default: 'c++'

  fuzz-seconds:
    description: 'The total time allotted for fuzzing in seconds.'
    required: true
    default: '600'

  dry-run:
    description: 'If set to true, runs without reporting failures.'
    required: false
    default: 'false'

  sanitizer:
    description: 'The sanitizer to run the fuzzers with.'
    required: false
    default: 'address'

  mode:
    description: |
      The mode to run fuzzers in. Options:
        - code-change: for fuzzing PRs or commits
        - batch: for full project fuzzing
        - coverage: for coverage generation
        - prune: for corpus pruning
    required: false
    default: 'code-change'

  github-token:
    description: |
      GitHub API token. Use "secrets.GITHUB_TOKEN" in workflows.
      DO NOT hardcode the token.
    required: false

  report-unreproducible-crashes:
    description: 'Whether to report unreproducible crashes.'
    required: false
    default: 'false'

  minimize-crashes:
    description: 'Whether to minimize reportable crashes.'
    required: false
    default: 'false'

  parallel-fuzzing:
    description: |
      Cores to use for fuzzing:
        - true: all available cores
        - false: single core
        - or a specific number
    required: false
    default: 'false'

  output-sarif:
    description: 'Whether to output fuzzing results in SARIF format.'
    required: false
    default: 'false'

  report-timeouts:
    description: 'Whether to report failures caused by timeouts.'
    required: false
    default: 'true'

  report-ooms:
    description: 'Whether to report failures caused by OOM (Out of Memory).'
    required: false
    default: 'true'

runs:
  using: 'docker'
  image: '../../../run_fuzzers.Dockerfile'
  env:
    OSS_FUZZ_PROJECT_NAME: ${{ inputs.oss-fuzz-project-name }}
    LANGUAGE: ${{ inputs.language }}
    FUZZ_SECONDS: ${{ inputs.fuzz-seconds }}
    DRY_RUN: ${{ inputs.dry-run }}
    SANITIZER: ${{ inputs.sanitizer }}
    MODE: ${{ inputs.mode }}
    GITHUB_TOKEN: ${{ inputs.github-token }}
    LOW_DISK_SPACE: 'True'
    REPORT_UNREPRODUCIBLE_CRASHES: ${{ inputs.report-unreproducible-crashes }}
    MINIMIZE_CRASHES: ${{ inputs.minimize-crashes }}
    CIFUZZ_DEBUG: 'True'
    CFL_PLATFORM: 'github'
    PARALLEL_FUZZING: ${{ inputs.parallel-fuzzing }}
    OUTPUT_SARIF: ${{ inputs.output-sarif }}
    REPORT_TIMEOUTS: ${{ inputs.report-timeouts }}
    REPORT_OOMS: ${{ inputs.report-ooms }}

